spring:
  application:
    name: common-item
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bz_shop?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: vps2020
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9010

eureka:
  client:
    serviceUrl:
      #eureka server url
      defaultZone: http://eureka-server:10010/eureka/

